import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./page.module.css";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className={styles.crumbs}>
            <ol>
              <li className={styles.crumb}>
                <Link href={"/"}>Статистика</Link>
              </li>
              <li className={styles.crumb}>
                <Link href="/cards">Номенклатура</Link>
              </li>
            </ol>
          </nav>{" "}
        </div>
        {children}
      </body>
    </html>
  );
}
